const playersPicksList = {
    'cagerage': [
        'Avengers_ Endgame',
        'Toy Story 4',
        'Spider-Man_ Far From Home',
        'The Lion King',
        'Aladdin (2019)',
        'The Secret Life of Pets 2',
        'Dark Phoenix',
        'Detective Pikachu',
        'Godzilla 2',
        'Once Upon a Time in Hollywood'
    ],
    'dabryk': [
        'Avengers_ Endgame',
        'The Lion King',
        'Spider-Man_ Far From Home',
        'The Secret Life of Pets 2',
        'Toy Story 4',
        'Hobbs & Shaw',
        'Godzilla 2',
        'Detective Pikachu',
        'Dark Phoenix',
        'Aladdin (2019)'
    ],
    'gab': [
        'Avengers_ Endgame',
        'Detective Pikachu',
        'Hobbs & Shaw',
        'Toy Story 4',
        'John Wick 3',
        'The Lion King',
        'Spider-Man_ Far From Home',
        'Godzilla 2',
        'Men in Black International',
        'The Secret Life of Pets 2'
    ],
    'hectorl': [
        'Avengers_ Endgame',
        'The Lion King',
        'Toy Story 4',
        'The Secret Life of Pets 2',
        'Detective Pikachu',
        'Spider-Man_ Far From Home',
        'Hobbs & Shaw',
        'Aladdin (2019)',
        'Godzilla 2',
        'Child\'s Play (2019)'
    ],
    'pambas': [
        'Avengers_ Endgame',
        'The Lion King',
        'Toy Story 4',
        'The Secret Life of Pets 2',
        'Spider-Man_ Far From Home',
        'Godzilla 2',
        'Detective Pikachu',
        'Hobbs & Shaw',
        'Aladdin (2019)',
        'Men in Black International'
    ],
    'bobbym116': [
        'Detective Pikachu',
        'John Wick 3',
        'Dark Phoenix',
        'Meeting Gorbachev',
        'Aladdin (2019)',
        'Crawl',
        'Dora and the Lost City of Gold',
        'Godzilla 2',
        'Spider-Man_ Far From Home',
        'Toy Story 4'
    ],
    'cassie': [
        'Avengers_ Endgame',
        'Aladdin (2019)',
        'Men in Black International',
        'Godzilla 2',
        'The Lion King',
        'A Dog\'s Journey',
        'The Secret Life of Pets 2',
        'Detective Pikachu',
        '47 Meters Down_ Uncaged',
        'Toy Story 4'
    ],
    'daiisdead': [
        'Avengers_ Endgame',
        'Hobbs & Shaw',
        'John Wick 3',
        'Spider-Man_ Far From Home',
        'Detective Pikachu',
        'Once Upon a Time in Hollywood',
        'Artemis Fowl',
        'The Lion King',
        'Toy Story 4',
        'The New Mutants'
    ],
    'dave': [
        'Avengers_ Endgame',
        'The Lion King',
        'Toy Story 4',
        'Spider-Man_ Far From Home',
        'Hobbs & Shaw',
        'Detective Pikachu',
        'The Secret Life of Pets 2',
        'Godzilla 2',
        'Men in Black International',
        'Aladdin (2019)'
    ],
    'jmoy': [
        'Avengers_ Endgame',
        'Toy Story 4',
        'The Lion King',
        'Aladdin (2019)',
        'Spider-Man_ Far From Home',
        'The Secret Life of Pets 2',
        'Detective Pikachu',
        'Hobbs & Shaw',
        'Rocketman',
        'Dora and the Lost City of Gold'
    ],
    'jonesetc': [
        'Avengers_ Endgame',
        'Toy Story 4',
        'Detective Pikachu',
        'The Lion King',
        'Spider-Man_ Far From Home',
        'Aladdin (2019)',
        'The Secret Life of Pets 2',
        'John Wick 3',
        'Hobbs & Shaw',
        'Dark Phoenix'
    ],
    'littlerob': [
        'Avengers_ Endgame',
        'Toy Story 4',
        'The Lion King',
        'Spider-Man_ Far From Home',
        'The Secret Life of Pets 2',
        'Once Upon a Time in Hollywood',
        'Men in Black International',
        'Godzilla 2',
        'John Wick 3',
        'Dark Phoenix'
    ],
    'midsommar': [
        'Avengers_ Endgame',
        'The Lion King',
        'Detective Pikachu',
        'Toy Story 4',
        'Aladdin (2019)',
        'The Secret Life of Pets 2',
        'Hobbs & Shaw',
        'Spider-Man_ Far From Home',
        'John Wick 3',
        'Godzilla 2'
    ],
    'sarad712': [
        'Avengers_ Endgame',
        'Dark Phoenix',
        'Spider-Man_ Far From Home',
        'Once Upon a Time in Hollywood',
        'Toy Story 4',
        'The Lion King',
        'The New Mutants',
        'Godzilla 2',
        'Men in Black International',
        'John Wick 3'
    ],
    'janaki': [
        'Avengers_ Endgame',
        'Toy Story 4',
        'The Lion King',
        'Hobbs & Shaw',
        'Men in Black International',
        'Detective Pikachu',
        'Rocketman',
        'Aladdin (2019)',
        'Spider-Man_ Far From Home',
        'Dark Phoenix'
    ]
};

export default playersPicksList;